name: Build and test project
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Bundle
        run: npm run bundle

      - name: Package
        run: npm run package-plugin

  test:
    runs-on: ubuntu-latest
    name: Test project
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Diff PR test coverage vs default branch
        id: testCoverageDiff
        if: ${{ github.event_name == 'pull_request' }}
        uses: anuraag016/Jest-Coverage-Diff@V1.4
        with:
          fullCoverageDiff: false
          afterSwitchCommand: "npm ci"
          delta: 0.5
